kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  name: run-helloworld-from-git
spec:
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/prietyc123/dance-test
      - name: branch
        value: main
      - name: pathInRepo
        value: pipelines/helloworld.yaml
